---
    :concurrency: 1
    :queues:
      - default
      - mailers
      - scheduler
    
    :schedule:
      scraper_webuy:
        # At every 43rd minute past every hour from 9 through 17 on every day-of-week from Monday through Saturday
        cron: '0 7 * * *'
        queue: scheduler
        enabled: true
        class: ScrapeLinkedin